//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_STOK4.Models.ENTITY
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Mvc_DbstokEntities2 : DbContext
    {
        public Mvc_DbstokEntities2()
            : base("name=Mvc_DbstokEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TBLKATEQORILER> TBLKATEQORILERs { get; set; }
        public virtual DbSet<TBLMUSDERILER> TBLMUSDERILERs { get; set; }
        public virtual DbSet<TBLSATISLAR> TBLSATISLARs { get; set; }
        public virtual DbSet<TBLURUNLER> TBLURUNLERs { get; set; }
    }
}
